// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQw3ig9GNgznSCbTzINeXKuYqzD0OgbMs',
    appId: '1:401309111879:web:1a8e1f0da087e8d1230362',
    messagingSenderId: '401309111879',
    projectId: 'stryde-278e4',
    authDomain: 'stryde-278e4.firebaseapp.com',
    storageBucket: 'stryde-278e4.firebasestorage.app',
    measurementId: 'G-XTEJ5FMSBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg0BuK-PYj5emnzdgYFne4oLmvLr1Kld0',
    appId: '1:401309111879:android:77da196ee7c910f4230362',
    messagingSenderId: '401309111879',
    projectId: 'stryde-278e4',
    storageBucket: 'stryde-278e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGndgW0ky2XlCS-HJgeo-hDrpIKC3pFuc',
    appId: '1:401309111879:ios:0e27d3e4512df4bf230362',
    messagingSenderId: '401309111879',
    projectId: 'stryde-278e4',
    storageBucket: 'stryde-278e4.firebasestorage.app',
    iosBundleId: 'com.example.stryde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGndgW0ky2XlCS-HJgeo-hDrpIKC3pFuc',
    appId: '1:401309111879:ios:0e27d3e4512df4bf230362',
    messagingSenderId: '401309111879',
    projectId: 'stryde-278e4',
    storageBucket: 'stryde-278e4.firebasestorage.app',
    iosBundleId: 'com.example.stryde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQw3ig9GNgznSCbTzINeXKuYqzD0OgbMs',
    appId: '1:401309111879:web:6fc7ea989e365806230362',
    messagingSenderId: '401309111879',
    projectId: 'stryde-278e4',
    authDomain: 'stryde-278e4.firebaseapp.com',
    storageBucket: 'stryde-278e4.firebasestorage.app',
    measurementId: 'G-FQZWVMXQHX',
  );
}
